// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.18.0
// source: protos/gardenmangement.proto

package gardenmangement

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bog' moduli
type Garden struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId   string  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name     string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type     string  `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	AreaSq   float64 `protobuf:"fixed64,5,opt,name=area_sq,json=areaSq,proto3" json:"area_sq,omitempty"`
	CreateAt string  `protobuf:"bytes,6,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt string  `protobuf:"bytes,7,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
}

func (x *Garden) Reset() {
	*x = Garden{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Garden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Garden) ProtoMessage() {}

func (x *Garden) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Garden.ProtoReflect.Descriptor instead.
func (*Garden) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{0}
}

func (x *Garden) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Garden) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Garden) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Garden) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Garden) GetAreaSq() float64 {
	if x != nil {
		return x.AreaSq
	}
	return 0
}

func (x *Garden) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *Garden) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

// O'simlik moduli
type Plant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GardenId     string `protobuf:"bytes,2,opt,name=garden_id,json=gardenId,proto3" json:"garden_id,omitempty"`
	Species      string `protobuf:"bytes,3,opt,name=species,proto3" json:"species,omitempty"`
	Quantity     int32  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PlantingDate string `protobuf:"bytes,5,opt,name=planting_date,json=plantingDate,proto3" json:"planting_date,omitempty"`
	Status       string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Plant) Reset() {
	*x = Plant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plant) ProtoMessage() {}

func (x *Plant) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plant.ProtoReflect.Descriptor instead.
func (*Plant) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{1}
}

func (x *Plant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plant) GetGardenId() string {
	if x != nil {
		return x.GardenId
	}
	return ""
}

func (x *Plant) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *Plant) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Plant) GetPlantingDate() string {
	if x != nil {
		return x.PlantingDate
	}
	return ""
}

func (x *Plant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Parvarish kundalik moduli
type CareLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlantId  string `protobuf:"bytes,2,opt,name=plant_id,json=plantId,proto3" json:"plant_id,omitempty"`
	Action   string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Notes    string `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	LoggedAt string `protobuf:"bytes,5,opt,name=logged_at,json=loggedAt,proto3" json:"logged_at,omitempty"`
}

func (x *CareLog) Reset() {
	*x = CareLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CareLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareLog) ProtoMessage() {}

func (x *CareLog) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareLog.ProtoReflect.Descriptor instead.
func (*CareLog) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{2}
}

func (x *CareLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CareLog) GetPlantId() string {
	if x != nil {
		return x.PlantId
	}
	return ""
}

func (x *CareLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CareLog) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CareLog) GetLoggedAt() string {
	if x != nil {
		return x.LoggedAt
	}
	return ""
}

type CreateGardenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Garden *Garden `protobuf:"bytes,1,opt,name=garden,proto3" json:"garden,omitempty"`
}

func (x *CreateGardenRequest) Reset() {
	*x = CreateGardenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGardenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGardenRequest) ProtoMessage() {}

func (x *CreateGardenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGardenRequest.ProtoReflect.Descriptor instead.
func (*CreateGardenRequest) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGardenRequest) GetGarden() *Garden {
	if x != nil {
		return x.Garden
	}
	return nil
}

type CreateGardenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CreateGardenResponse) Reset() {
	*x = CreateGardenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGardenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGardenResponse) ProtoMessage() {}

func (x *CreateGardenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGardenResponse.ProtoReflect.Descriptor instead.
func (*CreateGardenResponse) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGardenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateGardenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetGardenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGardenRequest) Reset() {
	*x = GetGardenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGardenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGardenRequest) ProtoMessage() {}

func (x *GetGardenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGardenRequest.ProtoReflect.Descriptor instead.
func (*GetGardenRequest) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{5}
}

func (x *GetGardenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGardenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	AreaSqm string `protobuf:"bytes,4,opt,name=area_sqm,json=areaSqm,proto3" json:"area_sqm,omitempty"`
}

func (x *GetGardenResponse) Reset() {
	*x = GetGardenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGardenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGardenResponse) ProtoMessage() {}

func (x *GetGardenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGardenResponse.ProtoReflect.Descriptor instead.
func (*GetGardenResponse) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{6}
}

func (x *GetGardenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetGardenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGardenResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetGardenResponse) GetAreaSqm() string {
	if x != nil {
		return x.AreaSqm
	}
	return ""
}

type UpdateGardenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Garden *Garden `protobuf:"bytes,1,opt,name=garden,proto3" json:"garden,omitempty"`
}

func (x *UpdateGardenRequest) Reset() {
	*x = UpdateGardenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGardenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGardenRequest) ProtoMessage() {}

func (x *UpdateGardenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGardenRequest.ProtoReflect.Descriptor instead.
func (*UpdateGardenRequest) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGardenRequest) GetGarden() *Garden {
	if x != nil {
		return x.Garden
	}
	return nil
}

type UpdateGardenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateGardenResponse) Reset() {
	*x = UpdateGardenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGardenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGardenResponse) ProtoMessage() {}

func (x *UpdateGardenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGardenResponse.ProtoReflect.Descriptor instead.
func (*UpdateGardenResponse) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGardenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteGardenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteGardenRequest) Reset() {
	*x = DeleteGardenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGardenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGardenRequest) ProtoMessage() {}

func (x *DeleteGardenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGardenRequest.ProtoReflect.Descriptor instead.
func (*DeleteGardenRequest) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteGardenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGardenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteGardenResponse) Reset() {
	*x = DeleteGardenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGardenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGardenResponse) ProtoMessage() {}

func (x *DeleteGardenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGardenResponse.ProtoReflect.Descriptor instead.
func (*DeleteGardenResponse) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteGardenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserGardensRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserGardensRequest) Reset() {
	*x = GetUserGardensRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserGardensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGardensRequest) ProtoMessage() {}

func (x *GetUserGardensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGardensRequest.ProtoReflect.Descriptor instead.
func (*GetUserGardensRequest) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserGardensRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserGardensResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gardens []*Garden `protobuf:"bytes,1,rep,name=gardens,proto3" json:"gardens,omitempty"`
}

func (x *GetUserGardensResponse) Reset() {
	*x = GetUserGardensResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserGardensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGardensResponse) ProtoMessage() {}

func (x *GetUserGardensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGardensResponse.ProtoReflect.Descriptor instead.
func (*GetUserGardensResponse) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserGardensResponse) GetGardens() []*Garden {
	if x != nil {
		return x.Gardens
	}
	return nil
}

type CreatePlantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plant *Plant `protobuf:"bytes,1,opt,name=plant,proto3" json:"plant,omitempty"`
}

func (x *CreatePlantRequest) Reset() {
	*x = CreatePlantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlantRequest) ProtoMessage() {}

func (x *CreatePlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlantRequest.ProtoReflect.Descriptor instead.
func (*CreatePlantRequest) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePlantRequest) GetPlant() *Plant {
	if x != nil {
		return x.Plant
	}
	return nil
}

type CreatePlantReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreatePlantReponse) Reset() {
	*x = CreatePlantReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlantReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlantReponse) ProtoMessage() {}

func (x *CreatePlantReponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlantReponse.ProtoReflect.Descriptor instead.
func (*CreatePlantReponse) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePlantReponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPlantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GardenId string `protobuf:"bytes,1,opt,name=garden_id,json=gardenId,proto3" json:"garden_id,omitempty"`
}

func (x *GetPlantRequest) Reset() {
	*x = GetPlantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantRequest) ProtoMessage() {}

func (x *GetPlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantRequest.ProtoReflect.Descriptor instead.
func (*GetPlantRequest) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{15}
}

func (x *GetPlantRequest) GetGardenId() string {
	if x != nil {
		return x.GardenId
	}
	return ""
}

type GetPlantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plants []*Plant `protobuf:"bytes,1,rep,name=plants,proto3" json:"plants,omitempty"`
}

func (x *GetPlantResponse) Reset() {
	*x = GetPlantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantResponse) ProtoMessage() {}

func (x *GetPlantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantResponse.ProtoReflect.Descriptor instead.
func (*GetPlantResponse) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{16}
}

func (x *GetPlantResponse) GetPlants() []*Plant {
	if x != nil {
		return x.Plants
	}
	return nil
}

type UpdatePlantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plant *Plant `protobuf:"bytes,1,opt,name=plant,proto3" json:"plant,omitempty"`
}

func (x *UpdatePlantRequest) Reset() {
	*x = UpdatePlantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlantRequest) ProtoMessage() {}

func (x *UpdatePlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlantRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlantRequest) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{17}
}

func (x *UpdatePlantRequest) GetPlant() *Plant {
	if x != nil {
		return x.Plant
	}
	return nil
}

type UpdatePlantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdatePlantResponse) Reset() {
	*x = UpdatePlantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlantResponse) ProtoMessage() {}

func (x *UpdatePlantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlantResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlantResponse) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{18}
}

func (x *UpdatePlantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeletePlantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePlantRequest) Reset() {
	*x = DeletePlantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlantRequest) ProtoMessage() {}

func (x *DeletePlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlantRequest.ProtoReflect.Descriptor instead.
func (*DeletePlantRequest) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{19}
}

func (x *DeletePlantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePlantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeletePlantResponse) Reset() {
	*x = DeletePlantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlantResponse) ProtoMessage() {}

func (x *DeletePlantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlantResponse.ProtoReflect.Descriptor instead.
func (*DeletePlantResponse) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{20}
}

func (x *DeletePlantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateCareLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CareLog *CareLog `protobuf:"bytes,1,opt,name=care_log,json=careLog,proto3" json:"care_log,omitempty"`
}

func (x *CreateCareLogRequest) Reset() {
	*x = CreateCareLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCareLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCareLogRequest) ProtoMessage() {}

func (x *CreateCareLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCareLogRequest.ProtoReflect.Descriptor instead.
func (*CreateCareLogRequest) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{21}
}

func (x *CreateCareLogRequest) GetCareLog() *CareLog {
	if x != nil {
		return x.CareLog
	}
	return nil
}

type CreateCareLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateCareLogResponse) Reset() {
	*x = CreateCareLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCareLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCareLogResponse) ProtoMessage() {}

func (x *CreateCareLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCareLogResponse.ProtoReflect.Descriptor instead.
func (*CreateCareLogResponse) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{22}
}

func (x *CreateCareLogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCareLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlantId string `protobuf:"bytes,1,opt,name=plant_id,json=plantId,proto3" json:"plant_id,omitempty"`
}

func (x *GetCareLogRequest) Reset() {
	*x = GetCareLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCareLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCareLogRequest) ProtoMessage() {}

func (x *GetCareLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCareLogRequest.ProtoReflect.Descriptor instead.
func (*GetCareLogRequest) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{23}
}

func (x *GetCareLogRequest) GetPlantId() string {
	if x != nil {
		return x.PlantId
	}
	return ""
}

type GetCareLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CareLog []*CareLog `protobuf:"bytes,1,rep,name=care_log,json=careLog,proto3" json:"care_log,omitempty"`
}

func (x *GetCareLogResponse) Reset() {
	*x = GetCareLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_gardenmangement_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCareLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCareLogResponse) ProtoMessage() {}

func (x *GetCareLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_gardenmangement_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCareLogResponse.ProtoReflect.Descriptor instead.
func (*GetCareLogResponse) Descriptor() ([]byte, []int) {
	return file_protos_gardenmangement_proto_rawDescGZIP(), []int{24}
}

func (x *GetCareLogResponse) GetCareLog() []*CareLog {
	if x != nil {
		return x.CareLog
	}
	return nil
}

var File_protos_gardenmangement_proto protoreflect.FileDescriptor

var file_protos_gardenmangement_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x6d,
	0x61, 0x6e, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x22, 0xac, 0x01, 0x0a, 0x06, 0x47, 0x61, 0x72, 0x64, 0x65,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x73, 0x71, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x72, 0x65, 0x61, 0x53, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0xa7, 0x01, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x70, 0x65, 0x63, 0x69, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x6e, 0x74,
	0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x7f, 0x0a, 0x07, 0x43, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c,
	0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f,
	0x74, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x3d, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x67, 0x61, 0x72, 0x64, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x2e, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x52, 0x06, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x22,
	0x4a, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x22, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x6f, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x73, 0x71,
	0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x72, 0x65, 0x61, 0x53, 0x71, 0x6d,
	0x22, 0x3d, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x67, 0x61, 0x72, 0x64, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x2e, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x52, 0x06, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x22,
	0x30, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x72, 0x64, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x30, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x2e, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x52, 0x07, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x73,
	0x22, 0x39, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x50,
	0x6c, 0x61, 0x6e, 0x74, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x22, 0x2e, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x06,
	0x70, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x22, 0x39, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x05,
	0x70, 0x6c, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x61,
	0x72, 0x64, 0x65, 0x6e, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x6e,
	0x74, 0x22, 0x2f, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x42, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x43, 0x61, 0x72,
	0x65, 0x4c, 0x6f, 0x67, 0x52, 0x07, 0x63, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x22, 0x31, 0x0a,
	0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x2e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x40, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x65, 0x5f, 0x6c,
	0x6f, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65,
	0x6e, 0x2e, 0x43, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x07, 0x63, 0x61, 0x72, 0x65, 0x4c,
	0x6f, 0x67, 0x32, 0xad, 0x06, 0x0a, 0x0d, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61,
	0x72, 0x64, 0x65, 0x6e, 0x12, 0x1b, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x49, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x12,
	0x1b, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47,
	0x61, 0x72, 0x64, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67,
	0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x61, 0x72, 0x64,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x12, 0x18, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61,
	0x72, 0x64, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x12, 0x1b, 0x2e,
	0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x72,
	0x64, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x61, 0x72,
	0x64, 0x65, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x61, 0x72,
	0x64, 0x65, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x72, 0x64, 0x65,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x61, 0x72, 0x64,
	0x65, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x47, 0x61, 0x72, 0x64, 0x65, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65,
	0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x67,
	0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x46, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x1a,
	0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x61, 0x72,
	0x64, 0x65, 0x6e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4c, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x67,
	0x12, 0x1c, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61,
	0x72, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x19, 0x2e, 0x67, 0x61,
	0x72, 0x64, 0x65, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x61, 0x72, 0x64, 0x65, 0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_gardenmangement_proto_rawDescOnce sync.Once
	file_protos_gardenmangement_proto_rawDescData = file_protos_gardenmangement_proto_rawDesc
)

func file_protos_gardenmangement_proto_rawDescGZIP() []byte {
	file_protos_gardenmangement_proto_rawDescOnce.Do(func() {
		file_protos_gardenmangement_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_gardenmangement_proto_rawDescData)
	})
	return file_protos_gardenmangement_proto_rawDescData
}

var file_protos_gardenmangement_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_protos_gardenmangement_proto_goTypes = []any{
	(*Garden)(nil),                 // 0: garden.Garden
	(*Plant)(nil),                  // 1: garden.Plant
	(*CareLog)(nil),                // 2: garden.CareLog
	(*CreateGardenRequest)(nil),    // 3: garden.CreateGardenRequest
	(*CreateGardenResponse)(nil),   // 4: garden.CreateGardenResponse
	(*GetGardenRequest)(nil),       // 5: garden.GetGardenRequest
	(*GetGardenResponse)(nil),      // 6: garden.GetGardenResponse
	(*UpdateGardenRequest)(nil),    // 7: garden.UpdateGardenRequest
	(*UpdateGardenResponse)(nil),   // 8: garden.UpdateGardenResponse
	(*DeleteGardenRequest)(nil),    // 9: garden.DeleteGardenRequest
	(*DeleteGardenResponse)(nil),   // 10: garden.DeleteGardenResponse
	(*GetUserGardensRequest)(nil),  // 11: garden.GetUserGardensRequest
	(*GetUserGardensResponse)(nil), // 12: garden.GetUserGardensResponse
	(*CreatePlantRequest)(nil),     // 13: garden.CreatePlantRequest
	(*CreatePlantReponse)(nil),     // 14: garden.CreatePlantReponse
	(*GetPlantRequest)(nil),        // 15: garden.GetPlantRequest
	(*GetPlantResponse)(nil),       // 16: garden.GetPlantResponse
	(*UpdatePlantRequest)(nil),     // 17: garden.UpdatePlantRequest
	(*UpdatePlantResponse)(nil),    // 18: garden.UpdatePlantResponse
	(*DeletePlantRequest)(nil),     // 19: garden.DeletePlantRequest
	(*DeletePlantResponse)(nil),    // 20: garden.DeletePlantResponse
	(*CreateCareLogRequest)(nil),   // 21: garden.CreateCareLogRequest
	(*CreateCareLogResponse)(nil),  // 22: garden.CreateCareLogResponse
	(*GetCareLogRequest)(nil),      // 23: garden.GetCareLogRequest
	(*GetCareLogResponse)(nil),     // 24: garden.GetCareLogResponse
}
var file_protos_gardenmangement_proto_depIdxs = []int32{
	0,  // 0: garden.CreateGardenRequest.garden:type_name -> garden.Garden
	0,  // 1: garden.UpdateGardenRequest.garden:type_name -> garden.Garden
	0,  // 2: garden.GetUserGardensResponse.gardens:type_name -> garden.Garden
	1,  // 3: garden.CreatePlantRequest.plant:type_name -> garden.Plant
	1,  // 4: garden.GetPlantResponse.plants:type_name -> garden.Plant
	1,  // 5: garden.UpdatePlantRequest.plant:type_name -> garden.Plant
	2,  // 6: garden.CreateCareLogRequest.care_log:type_name -> garden.CareLog
	2,  // 7: garden.GetCareLogResponse.care_log:type_name -> garden.CareLog
	3,  // 8: garden.GardenService.CreateGarden:input_type -> garden.CreateGardenRequest
	7,  // 9: garden.GardenService.UpdateGarden:input_type -> garden.UpdateGardenRequest
	5,  // 10: garden.GardenService.GetGarden:input_type -> garden.GetGardenRequest
	9,  // 11: garden.GardenService.DeleteGareden:input_type -> garden.DeleteGardenRequest
	11, // 12: garden.GardenService.GetUserGardens:input_type -> garden.GetUserGardensRequest
	13, // 13: garden.GardenService.CreatePlant:input_type -> garden.CreatePlantRequest
	15, // 14: garden.GardenService.GetPlant:input_type -> garden.GetPlantRequest
	17, // 15: garden.GardenService.UpdatePlant:input_type -> garden.UpdatePlantRequest
	19, // 16: garden.GardenService.DeletePlant:input_type -> garden.DeletePlantRequest
	21, // 17: garden.GardenService.CreateCareLog:input_type -> garden.CreateCareLogRequest
	23, // 18: garden.GardenService.GetCareLog:input_type -> garden.GetCareLogRequest
	4,  // 19: garden.GardenService.CreateGarden:output_type -> garden.CreateGardenResponse
	8,  // 20: garden.GardenService.UpdateGarden:output_type -> garden.UpdateGardenResponse
	6,  // 21: garden.GardenService.GetGarden:output_type -> garden.GetGardenResponse
	10, // 22: garden.GardenService.DeleteGareden:output_type -> garden.DeleteGardenResponse
	12, // 23: garden.GardenService.GetUserGardens:output_type -> garden.GetUserGardensResponse
	14, // 24: garden.GardenService.CreatePlant:output_type -> garden.CreatePlantReponse
	16, // 25: garden.GardenService.GetPlant:output_type -> garden.GetPlantResponse
	18, // 26: garden.GardenService.UpdatePlant:output_type -> garden.UpdatePlantResponse
	20, // 27: garden.GardenService.DeletePlant:output_type -> garden.DeletePlantResponse
	22, // 28: garden.GardenService.CreateCareLog:output_type -> garden.CreateCareLogResponse
	24, // 29: garden.GardenService.GetCareLog:output_type -> garden.GetCareLogResponse
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_protos_gardenmangement_proto_init() }
func file_protos_gardenmangement_proto_init() {
	if File_protos_gardenmangement_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_gardenmangement_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Garden); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Plant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CareLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGardenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGardenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetGardenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetGardenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateGardenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateGardenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteGardenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteGardenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserGardensRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserGardensResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePlantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*CreatePlantReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GetPlantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetPlantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*UpdatePlantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*UpdatePlantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*DeletePlantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*DeletePlantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*CreateCareLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*CreateCareLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*GetCareLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_gardenmangement_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*GetCareLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_gardenmangement_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_gardenmangement_proto_goTypes,
		DependencyIndexes: file_protos_gardenmangement_proto_depIdxs,
		MessageInfos:      file_protos_gardenmangement_proto_msgTypes,
	}.Build()
	File_protos_gardenmangement_proto = out.File
	file_protos_gardenmangement_proto_rawDesc = nil
	file_protos_gardenmangement_proto_goTypes = nil
	file_protos_gardenmangement_proto_depIdxs = nil
}
